// react-client/src/Fib.js
import React, {Component} from 'react';
import axios from 'axios';

class Fib extends Component {
    state = {
        seenIndexes: [],
        values: {},
        index: ''
    };

    componentDidMount() {
        this.fetchValues();
        this.fetchIndexes();
    }

    async fetchValues() {
        const values = await axios.get('/api/values/current');
        console.log(values.data);
        this.setState({
            values: values.data
        })

    }
    async fetchIndexes() {
        const seenIndexes = await axios.get('/api/values/all');
        this.setState({
            seenIndexes: seenIndexes.data
        })

    }
    handleSubmit = async event => {
        event.preventDefault();
    
        await axios.post('/api/values', {
          index: this.state.index
        });
        console.log(this.state.index);
        this.setState({ index: '' });
      };

      renderSeenIndexes() {
        if(this.state.seenIndexes) {
          return this.state.seenIndexes.map(({ number }) => number).join(', ');
        }
        return;
       
      }
    
      renderValues() {
        const entries = [];
    
        for (let key in this.state.values) {
          entries.push(
            <div key={key}>
              For index {key} I calculated {this.state.values[key]}
              
            </div>
          );
          console.log(this.state.values[key]);
        }
    
        return entries;
      }

    render() {
        return (
          <div>
            <form onSubmit={this.handleSubmit}>
              <label>Enter your index:</label>
              <input
                value={this.state.index}
                onChange={event => this.setState({ index: event.target.value })}
              />
              <button>Submit</button>
            </form>
    
            <h3>Indexes I have seen:</h3>
            {this.renderSeenIndexes()}
    
            <h3>Calculated Values:</h3>
            {this.renderValues()}
          </div>
        );
      }
}
export default Fib;

// vue-client/src/components/Fib.vue
<template>
<div>
    <form @submit.prevent="onSubmit">
        <label for="index">Enter your index</label>
        <input v-model="index"/>
        <button type="submit">Submit</button>

    </form>
    <h3>Indexes I have seen: <span v-for="(index,key) in seenIndexes" :key="key">{{index.number}}&nbsp;</span>  </h3>

    <h3 v-for="(value,index) in values" :key="index">For index {{index}} I calculated {{value}}</h3>

</div>
  
</template>

<script>
import axios from 'axios';

export default {
    data() {
        return {
            index:"",
            seenIndexes: [],
            values: {},
           
        }
    },
    created() {
        this.fetchValues();
        this.fetchIndexes();
    },
    methods: {
       async fetchValues() {
           const values = await axios.get('/api/values/current');
           this.values = values.data;
        },
        async fetchIndexes() {
            const indexes = await axios.get('/api/values/all');
            this.seenIndexes = indexes.data;
            console.log(indexes.data);
        },
        async onSubmit() {
            await axios.post('/api/values', {
                index: this.index
            });
            this.index = "";
        }
    }
}
</script>

<style>

</style>
